//
// Created by KOVAL Igor on 03/12/2016.
//

#ifndef LONGITUDINA2_EXPONENTIALBASEMANIFOLD_H
#define LONGITUDINA2_EXPONENTIALBASEMANIFOLD_H


class ExponentialBaseManifold {

};


#endif //LONGITUDINA2_EXPONENTIALBASEMANIFOLD_H
